name: QA Instance Retention

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      retention_hours:
        description: 'Hours before warning (default: 48)'
        required: false
        default: '48'
      inactivity_hours:
        description: 'Hours of inactivity before closing (default: 24)'
        required: false
        default: '24'

jobs:
  check-retention:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      packages: read

    steps:
      - name: Run Retention Check
        run: |
          docker run --rm \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_OWNER=${{ github.repository_owner }} \
            -e GITHUB_REPO=${{ github.event.repository.name }} \
            -e RETENTION_HOURS=${{ inputs.retention_hours || 48 }} \
            -e INACTIVITY_THRESHOLD_HOURS=${{ inputs.inactivity_hours || 24 }} \
            -e DEBUG=${{ inputs.debug || 'false' }} \
            doloresdei/qa-retention:1.0.4