name: QA Instance Retention

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'
      retention_hours:
        description: 'Hours before warning (default: 48)'
        required: false
        default: '48'
      inactivity_hours:
        description: 'Hours of inactivity before closing (default: 24)'
        required: false
        default: '24'

jobs:
  check-retention:
    runs-on: ubuntu-latest
    container:
      image: doloresdei/qa-retention:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RETENTION_HOURS: ${{ inputs.retention_hours || 48 }}
        INACTIVITY_THRESHOLD_HOURS: ${{ inputs.inactivity_hours || 24 }}
        DEBUG: ${{ inputs.debug || 'false' }}
    permissions:
      issues: write
      contents: read
      packages: read

    steps:
      - name: Run Retention Check
        run: deno run -A main.ts